CREATE SCHEMA `amp_backend` DEFAULT CHARACTER SET utf8;

CREATE TABLE amp_backend.item (
  ITEM_KEY BIGINT(20) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(256) NOT NULL,
  IMG_URL VARCHAR(512) NOT NULL,
  CONTENT TEXT NOT NULL,
  CREATE_DT DATETIME NOT NULL,
  UPDATE_DT DATETIME NULL,
  PRIMARY KEY (ITEM_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
